//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Restaurant.Models.Domin
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DbHolstentorEntities : DbContext
    {
        public DbHolstentorEntities()
            : base("name=DbHolstentorEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Tbl_Album> Tbl_Album { get; set; }
        public virtual DbSet<Tbl_EmailConfirmed> Tbl_EmailConfirmed { get; set; }
        public virtual DbSet<Tbl_Galerie> Tbl_Galerie { get; set; }
        public virtual DbSet<Tbl_Hochladen> Tbl_Hochladen { get; set; }
        public virtual DbSet<Tbl_Index> Tbl_Index { get; set; }
        public virtual DbSet<Tbl_IndexET> Tbl_IndexET { get; set; }
        public virtual DbSet<Tbl_Kategorie> Tbl_Kategorie { get; set; }
        public virtual DbSet<Tbl_Nachricht> Tbl_Nachricht { get; set; }
        public virtual DbSet<Tbl_Produkte> Tbl_Produkte { get; set; }
        public virtual DbSet<Tbl_RestPassword> Tbl_RestPassword { get; set; }
        public virtual DbSet<Tbl_Roles> Tbl_Roles { get; set; }
        public virtual DbSet<Tbl_Unterkategorie> Tbl_Unterkategorie { get; set; }
        public virtual DbSet<Tbl_UnterkategorieGalerie> Tbl_UnterkategorieGalerie { get; set; }
        public virtual DbSet<Tbl_Users> Tbl_Users { get; set; }
    }
}
