//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Restaurant.Models.Domin
{
    using Holstentor.Models.Plugin; // Add
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations; // Add

    public partial class Tbl_Unterkategorie
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_Unterkategorie()
        {
            this.Tbl_Produkte = new HashSet<Tbl_Produkte>();
            this.Tbl_UnterkategorieGalerie = new HashSet<Tbl_UnterkategorieGalerie>();
        }
    
        //public int ID { get; set; }
        //public bool ActivePassive { get; set; }
        //public Nullable<int> CategoryID { get; set; }
        //public string Description { get; set; }
        //public string FontName { get; set; }
        //public string Subtitle1 { get; set; }
        //public string Subtitle2 { get; set; }
        //public string Subtitle3 { get; set; }
        //public string TitleSubCategory { get; set; }

        public int ID { get; set; }
        [MaxLength(50, ErrorMessage = Message.MaxLengthMsgDer)]
        [Required(AllowEmptyStrings = false, ErrorMessage = Message.RequiredMsgDer)]
        [Display(Name = "Unterkategoriename")]
        public string TitleSubCategory { get; set; }
        [MaxLength(150, ErrorMessage = Message.MinLengthMsgDie)]
        [Display(Name = "Beschreibung")]
        public string Description { get; set; }
        public bool ActivePassive { get; set; }
        [MaxLength(30, ErrorMessage = Message.MinLengthMsgDie)]
        [Display(Name = "Schriftart")]
        public string FontName { get; set; }
        [MaxLength(50, ErrorMessage = Message.MinLengthMsgDer)]
        [Display(Name = "Untertitel-1")]
        public string Subtitle1 { get; set; }
        [MaxLength(50, ErrorMessage = Message.MinLengthMsgDer)]
        [Display(Name = "Untertitel-2")]
        public string Subtitle2 { get; set; }
        [MaxLength(50, ErrorMessage = Message.MinLengthMsgDer)]
        [Display(Name = "Untertitel-3")]
        public string Subtitle3 { get; set; }
        public Nullable<int> CategoryID { get; set; }

        public virtual Tbl_Kategorie Tbl_Kategorie { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Produkte> Tbl_Produkte { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_UnterkategorieGalerie> Tbl_UnterkategorieGalerie { get; set; }
    }
}
