//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Restaurant.Models.Domin
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_RestPassword
    {
        public string ID { get; set; }
        public System.DateTime Date { get; set; }
        public string UserID { get; set; }
        public string Password { get; set; }
        public string ConfirmPassword { get; set; }
    
        public virtual Tbl_Users Tbl_Users { get; set; }
    }
}
