//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Restaurant.Models.Domin
{
    using Holstentor.Models.Plugin; // Add
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations; // Add

    public partial class Tbl_Index
    {
        //public int IDIndex { get; set; }
        //public string Title { get; set; }
        //public string TypedText1 { get; set; }
        //public string TypedText2 { get; set; }
        //public string TypedText3 { get; set; }
        //public string TypedText4 { get; set; }
        //public string TypedText5 { get; set; }
        public int IDIndex { get; set; }
        [MaxLength(100, ErrorMessage = Message.MaxLengthMsgDer)]
        [Required(AllowEmptyStrings = false, ErrorMessage = Message.RequiredMsgDer)]
        [Display(Name = "Titel")]
        public string Title { get; set; }
        [MaxLength(300, ErrorMessage = Message.MaxLengthMsgDer)]
        [Required(AllowEmptyStrings = false, ErrorMessage = Message.RequiredMsgDer)]
        [Display(Name = "Untertitel-1")]
        public string TypedText1 { get; set; }
        [MaxLength(300, ErrorMessage = Message.MaxLengthMsgDer)]
        [Display(Name = "Untertitel-2")]
        public string TypedText2 { get; set; }
        [MaxLength(300, ErrorMessage = Message.MaxLengthMsgDer)]
        [Display(Name = "Untertitel-3")]
        public string TypedText3 { get; set; }
        [MaxLength(300, ErrorMessage = Message.MaxLengthMsgDer)]
        [Display(Name = "Untertitel-4")]
        public string TypedText4 { get; set; }
        [MaxLength(300, ErrorMessage = Message.MaxLengthMsgDer)]
        [Display(Name = "Untertitel-5")]
        public string TypedText5 { get; set; }
    }
}
