//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Restaurant.Models.Domin
{
    using Holstentor.Models.Plugin; // Add
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations; // Add

    public partial class Tbl_Produkte
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_Produkte()
        {
            this.Tbl_Galerie = new HashSet<Tbl_Galerie>();
        }

        //public int ID { get; set; }
        //public bool ActiveInactive { get; set; }
        //public Nullable<int> CategoryID { get; set; }
        //public System.DateTime Date { get; set; }
        //public string Description { get; set; }
        //public string Price1 { get; set; }
        //public string Price2 { get; set; }
        //public string Price3 { get; set; }
        //public Nullable<int> SubCategoryID { get; set; }
        //public string Title { get; set; }
        //public string UserID { get; set; }
        //public Nullable<int> Position { get; set; }

        public int ID { get; set; }
        [MaxLength(50, ErrorMessage = Message.MaxLengthMsgDer)]
        [Required(AllowEmptyStrings = false, ErrorMessage = Message.RequiredMsgDer)]
        [Display(Name = "Produkttitel")]
        public string Title { get; set; }
        [MaxLength(250, ErrorMessage = Message.MaxLengthMsgDie)]
        [Display(Name = "Beschreibung")]
        public string Description { get; set; }
        public Nullable<int> CategoryID { get; set; }
        public Nullable<int> SubCategoryID { get; set; }
        [MaxLength(5, ErrorMessage = Message.MaxLengthMsgDer)]
        [Required(AllowEmptyStrings = false, ErrorMessage = Message.RequiredMsgDer)]
        [Display(Name = "Preis-1")]
        public string Price1 { get; set; }
        [MaxLength(5, ErrorMessage = Message.MaxLengthMsgDer)]
        [Display(Name = "Preis-2")]
        public string Price2 { get; set; }
        [MaxLength(5, ErrorMessage = Message.MaxLengthMsgDer)]
        [Display(Name = "Preis-3")]
        public string Price3 { get; set; }
        public bool ActiveInactive { get; set; }
        public DateTime Date { get; set; }
        public string UserID { get; set; }
        public Nullable<int> Position { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Galerie> Tbl_Galerie { get; set; }
        public virtual Tbl_Kategorie Tbl_Kategorie { get; set; }
        public virtual Tbl_Unterkategorie Tbl_Unterkategorie { get; set; }
        public virtual Tbl_Users Tbl_Users { get; set; }
    }
}
