//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Restaurant.Models.Domin
{
    using Holstentor.Models.Plugin; // Add
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations; // Add

    public partial class Tbl_Hochladen
    {
        //public int ID { get; set; }
        //public string ImageAbout { get; set; }
        //public string ImageFooter { get; set; }
        //public string ImageGallery { get; set; }
        //public string Logo { get; set; }
        //public string Video { get; set; }

        public int ID { get; set; }
        [Required(AllowEmptyStrings = false, ErrorMessage = Message.RequiredMsgDas)]
        [Display(Name = "Video")]
        public string Video { get; set; }
        [Required(AllowEmptyStrings = false, ErrorMessage = Message.RequiredMsgDas)]
        [Display(Name = "Logo")]
        public string Logo { get; set; }
        [Required(AllowEmptyStrings = false, ErrorMessage = Message.RequiredMsgDas)]
        [Display(Name = "Foto")]
        public string ImageAbout { get; set; }
        [Required(AllowEmptyStrings = false, ErrorMessage = Message.RequiredMsgDas)]
        [Display(Name = "Foto")]
        public string ImageGallery { get; set; }
        [Required(AllowEmptyStrings = false, ErrorMessage = Message.RequiredMsgDas)]
        [Display(Name = "Foto")]
        public string ImageFooter { get; set; }
    }
}
