//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Restaurant.Models.Domin
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Nachricht
    {
        public int ID { get; set; }
        public bool Confirm { get; set; }
        public System.DateTime Date { get; set; }
        public Nullable<System.DateTime> DateUpdate { get; set; }
        public string Text { get; set; }
        public string TextAdmin { get; set; }
        public string UserIdRecive { get; set; }
        public string UserIdSend { get; set; }
    }
}
