//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Restaurant.Models.Domin
{
    using Holstentor.Models.Plugin; // Add
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations; // Add

    public partial class Tbl_Album
    {
        //public int ID { get; set; }
        //public System.DateTime Date { get; set; }
        //public string Image { get; set; }
        //public string NamePic { get; set; }

        public int ID { get; set; }
        [MaxLength(50, ErrorMessage = Message.MaxLengthMsgDer)]
        [Required(AllowEmptyStrings = false, ErrorMessage = Message.RequiredMsgDer)]
        [Display(Name = "Fotoname")]
        public string NamePic { get; set; }
        [Required(AllowEmptyStrings = false, ErrorMessage = Message.RequiredMsgDas)]
        [Display(Name = "Foto")]
        public string Image { get; set; }
        public DateTime Date { get; set; }
    }
}
