//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Restaurant.Models.Domin
{
    using Holstentor.Models.Plugin; // Add
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations; // Add

    public partial class Tbl_Kategorie
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_Kategorie()
        {
            this.Tbl_Produkte = new HashSet<Tbl_Produkte>();
            this.Tbl_Unterkategorie = new HashSet<Tbl_Unterkategorie>();
        }

        //public int ID { get; set; }
        //public bool ActivePassive { get; set; }
        //public string Description { get; set; }
        //public string FontName { get; set; }
        //public string TitleCategory { get; set; }

        public int ID { get; set; }
        [MaxLength(50, ErrorMessage = Message.MaxLengthMsgDer)]
        [Required(AllowEmptyStrings = false, ErrorMessage = Message.RequiredMsgDer)]
        [Display(Name = "Kategoriename")]
        public string TitleCategory { get; set; }
        [MaxLength(150, ErrorMessage = Message.MaxLengthMsgDie)]
        [Display(Name = "Beschreibung")]
        public string Description { get; set; }
        public bool ActivePassive { get; set; }
        [MaxLength(30, ErrorMessage = Message.MaxLengthMsgDie)]
        [Display(Name = "Schriftart")]
        public string FontName { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Produkte> Tbl_Produkte { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Unterkategorie> Tbl_Unterkategorie { get; set; }
    }
}
