//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Restaurant.Models.Domin
{
    using Holstentor.Models.Plugin; // Add
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations; // Add

    public partial class Tbl_IndexET
    {
        //public int IDIndex { get; set; }
        //public string City { get; set; }
        //public string Country { get; set; }
        //public string Description { get; set; }
        //public string Email { get; set; }
        //public string EmbedLinkGoogleMap { get; set; }
        //public string NameSite { get; set; }
        //public string Number { get; set; }
        //public string PhoneNumber { get; set; }
        //public string PostCode { get; set; }
        //public string Street { get; set; }
        public int IDIndex { get; set; }
        [Required(ErrorMessage = Message.RequiredMsgEmail)]
        [MaxLength(256, ErrorMessage = Message.MaxLengthMsgDie)]
        [EmailAddress(ErrorMessage = Message.Email)]
        [Display(Name = "E-Mail-Adresse")]
        public string Email { get; set; }
        [Required(AllowEmptyStrings = false, ErrorMessage = Message.RequiredMsgDie)]
        [Display(Name = "Telefonnummer")]
        public string PhoneNumber { get; set; }
        [Required(AllowEmptyStrings = false, ErrorMessage = Message.RequiredMsgDer)]
        [Display(Name = "Websitename")]
        public string NameSite { get; set; }
        [Required(AllowEmptyStrings = false, ErrorMessage = Message.RequiredMsgDie)]
        [Display(Name = "Straﬂe")]
        public string Street { get; set; }
        [Required(AllowEmptyStrings = false, ErrorMessage = Message.RequiredMsgDie)]
        [Display(Name = "Nummer")]
        public string Number { get; set; }
        [Required(AllowEmptyStrings = false, ErrorMessage = Message.RequiredMsgDie)]
        [Display(Name = "Postleitzahl")]
        public string PostCode { get; set; }
        [Required(AllowEmptyStrings = false, ErrorMessage = Message.RequiredMsgDie)]
        [Display(Name = "Stadt")]
        public string City { get; set; }
        [Required(AllowEmptyStrings = false, ErrorMessage = Message.RequiredMsgDas)]
        [Display(Name = "Land")]
        public string Country { get; set; }
        [Required(AllowEmptyStrings = false, ErrorMessage = Message.RequiredMsgDer)]
        [Display(Name = "Link (EmbedLinkGoogleMap)")]
        public string EmbedLinkGoogleMap { get; set; }
        [Required(AllowEmptyStrings = false, ErrorMessage = Message.RequiredMsgDie)]
        [Display(Name = "Beschreibung")]
        public string Description { get; set; }
    }
}
